// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDatabaseConfigs() {
  return window['go']['app']['App']['GetDatabaseConfigs']();
}

export function ListDbTables() {
  return window['go']['app']['App']['ListDbTables']();
}

export function ListTables(arg1) {
  return window['go']['app']['App']['ListTables'](arg1);
}
