// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {configs} from '../models';

export function GetDatabaseConfigs():Promise<Array<configs.DatabaseConfig>>;

export function Greet(arg1:string):Promise<string>;

export function ListDbTables():Promise<Array<string>>;

export function ListTables(arg1:string):Promise<Array<string>>;
